name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    # Add caching for npm dependencies
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env

    # Add caching for build output
    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: .next
        key: ${{ runner.OS }}-next-build-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
        restore-keys: |
          ${{ runner.OS }}-next-build-

    - name: Build project
      run: npm run build

    - name: Deploy to Digital Ocean
      env:
        HOST: 134.209.151.178
        USER: deploy
        PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" \
          --exclude='.git' \
          --exclude='node_modules' \
          ./ ${USER}@${HOST}:/var/www/magic/
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
          cd /var/www/magic
          pm2 restart magic  # Assuming your PM2 app is named 'magic'
        EOF

    - name: Cleanup
      if: always()
      run: rm -f private_key